spring:
  application:
  name: StudentManagment

  datasource:
    url: jdbc:postgresql://localhost:5432/managementDb
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # PAY ATTENTION, BE CAUTIOUS!!!
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000
springdoc:
  swagger-ui:
    path:/swagger-ui.html
